config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  root to: 'kittens#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, :age, :softness, :cuteness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      redirect_to kitten_path(@kitten.id), notice: 'Kitten has been created!'
    else
      flash.now[:alert] = 'Fields cannot be blank!'
      render :new
    end
  end
  
  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update(kitten_params)
      redirect_to kitten_path(@kitten.id), notice: 'Kitten has been updated!'
    else
      flash.now[:alert] = 'Fields cannot be blank!'
      render :edit
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    redirect_to root_path, notice: 'Kitten has been deleted!'
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>
<%= render "kittens/shared/form" %>
<%= link_to 'Delete', kitten_path(@kitten.id),
            data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>
<ul>
  <% @kittens.each do |kitten| %>
    <li>
      <h2><%= link_to kitten.name, kitten_path(kitten.id) %></h2> 
      <h5>
        <%= link_to 'Delete', kitten_path(kitten.id),
                data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
      </h5>
    </li>
  <% end %>
</ul>

app/views/kittens/new.html.erb
<h1>Create Kitten</h1>
<%= render "kittens/shared/form" %>

app/views/kittens/shared/_form.html.erb
<%= form_with model: @kitten do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'ex. Rex' %>
  </p>

  <p>
    <%= f.label :age %>
    <%= f.select :age, ['less than 1', '2', '3', '4', '5', '6','7', '8', '9', '10', '10+'], { include_blank: true } %>
  </p>

  <p>
    <%= f.label :cuteness %>
    <%= f.select :cuteness, ['extremely cute', 'very cute', 'a little cute', 'not cute'], { include_blank: true } %>
  </p>

  <p>
    <%= f.label :softness %>
    <%= f.select :softness, ['extremely soft', 'very soft', 'a little soft', 'not soft'], { include_blank: true } %>
  </p>

  <p><%= f.submit %></p>
<% end %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<ul>
  <li>
    <h3>Age - <%= @kitten.age %></h3>
  </li>
  <li>
    <h3>Softness - <%= @kitten.softness %></h3>
  </li>
  <li>
    <h3>Cuteness - <%= @kitten.cuteness %></h3>
  </li>
</ul>
<%= link_to 'Edit', edit_kitten_path(@kitten.id) %>
<%= link_to 'Delete', kitten_path(@kitten.id),
            data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= button_to 'Kittens', kittens_path, method: :get %>
    <%= button_to 'Create Kitten', new_kitten_path, method: :get %>

    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>